### ISSUE TITLE
number of tweets received by get_timeline

### ISSUE THREAD

**Issue by neuwirthe** [mkearney/rtweet#32] opened 2016-10-24 08:10 UTC
I requested 2000 tweets for about 50 people, and when their timeline had more than that, I received 1990 or 1991 for each one.
This is not a serious bug, but strange behavior.
DO you see a reason for this?

**Comment by mkearney** [comment] 2016-10-24 16:47
There are two reasons for it:  
1. When a user deletes a tweet, Twitter's API will sometimes return fewer tweets than the desired count. If memory serves, you can request 100 tweets per request, and Twitter will sometimes include deleted tweets in those counts. Unfortunately, there is no way to confirm whether when exactly a tweet was deleted or originally posted.

2. Duplicate tweets. I'm not sure what the cause of this is. It seems to happen between [and not within] requests, so it could be the user tweeted while you were making requests or it could just be a glitch in Twitter's REST database.

Now that you mention it, though, I'm going to make sure my `unique` function is behaving like it should. If a user posts the same tweet twice, for example, I want to make sure it returns both tweets.

**Comment by neuwirthe** [comment] 2016-10-25 15:47
Well, I downloaded tweets for 51 users, and I requested 2000 tweets each time.
I got 1990 in about 45 cases, 1991 in one case, and fewer in the remaining cases (these people hat deleted tweets).
That I got 1990 in most cases seems to indicate another problem.

**Comment by mkearney** [comment] 2016-10-25 17:01
Agreed. I didn't realize it was happening so frequently. I just poked around some I couldn't locate the problem. My best guess is the function is returning the last tweet from the previous call. Since the count limit is 200 (for get_timeline and get_favorites), that would explain why you're 10 tweets short. I'd like to verify this before closing it, though, so I'll hopefully have time to do so a little later this week.

Thanks again for reporting issues. By all means, please keep posting them if you think something is wrong or if something should be changed. I'm eager for feedback and user-testing.

**Comment by neuwirthe** [comment] 2016-10-25 18:12
Well, I downloaded tweets for 51 users, and I requested 2000 tweets each time.
I got 1990 in about 45 cases, 1991 in one case, and fewer in the remaining cases (these people hat deleted tweets).
That I got 1990 in most cases seems to indicate another problem.

**Comment by mkearney** [comment] 2016-10-26 20:52
My hunch was correct. The first tweet returned for each call is a duplicate. I can fix this so the functions return the specified number, but that would require some sacrifice to efficiency at least in terms of API rate limits (to return 1000 unique tweets, it would require an 11th request for those 9 extra tweets, which would be functionally throwing away 91 tweets).

```{r}
> rt <- search_tweets("hillaryclinton OR realdonaldtrump", n = 1000, parse = FALSE)
> rt <- lapply(rt, function(x) x$statuses[1:4])
> rt <- do.call("rbind", rt)
> NROW(rt)
[1] 1000
NROW(unique(rt))
[1] 991
> which(duplicated(rt))
[1] 101 201 301 401 501 601 701 801 901
```

**Closed** 2016-10-31 20:33 UTC
