### ISSUE TITLE
since_id is not recognize in get_timeline

### ISSUE THREAD

**Issue by Felipe1990** [mkearney/rtweet#147] opened 2017-12-01 01:33 UTC
From what I understand from the options of the function get_timeline one could pass de option since_id to the API query but when I use it I get the same results as if I dont set it.
Should I write it in a particular way?

Thank you

**Comment by JBGruber** [comment] 2017-12-13 21:46
I came here to ask the same question. I'm collecting tweets on a small server and when trying to collect all tweets from a certain user my machine runs out of memory.

The parameter is described here, so it should theoretically work:
https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html

To me what looks like it could cause this problem is that `do.call("get_timeline_", args)` in your timeline.R script does not pass on the ellipsis. Maybe something like [this](https://stackoverflow.com/questions/3142731/r-using-a-list-for-ellipsis-arguments) would do the trick?

**Comment by mkearney** [comment] 2018-01-05 20:40
As demonstrated in the code below, using the `since_id` parameter in `get_timeline()` should be fairly straight forward–at least as of version 0.6.0.

## Example of using since_id with get_timeline()

First, for demonstration purposes, collect the 1,000 most recent tweets posted by a user–for this example, I'm using my own account.

``` r
## load rtweet
library(rtweet)

## get most recent 1,000 tweets from given user
rt <- get_timeline("kearneymw", n = 1000)
```

In theory, users would only really need to use the `since_id` parameter if they wanted to update timeline data for a given user(s). So, let's pretend that we only collected the last 500(ish) tweets of the 1,000 tweets returned from the code above<sup>1</sup>.

``` r
## subset rows 501:1000(ish) and store as rt_old
rt_old <- rt[501:nrow(rt), ]
```

The `since_id` parameter allows you to collect all tweets posted ***since*** a given tweet<sup>2. So, the code below sets `since_id` to be equal to the `status_id` of the oldest tweet in `rt_old`.

``` r
## set oldest status ID as since_id
(since_id <- rt$status_id[nrow(rt)])
[1] "892729976121962496"
```

Next, we pass along the `since_id` value in a `get_timeline()` call, asking for 500 tweets posted ***since*** status `892729976121962496`<sup>2</sup>.

``` r
## get up to 500 tweets posted since the since_id status
rt_new <- get_timeline("kearneymw", n = 500, since_id = since_id)
```

Now, once we combine all data...

``` r
## merge data into single data frame
rt2 <- do_call_rbind(list(rt_old, rt_new))
```

We should have all the same tweets in `rt2` as we did in `rt`.

``` r
## test if all status IDs from since_id method match original data set
all(rt2$status_id %in% rt$status_id)
[1] TRUE
```

<sup>1</sup> By default, `get_timeline()` returns tweets ordered from newest to oldest, so by selecting the tail end of tweets, the code functionally selects the oldest tweets contained in data.

<sup>2</sup> Complications arise when the user has posted greater than 3,200 tweets (the max number of tweets returned by the `statuses/user_timeline` API) since posting the status set as the `since_id`. In this case, I believe, Twitter will just return oldest tweets possible (so, starting at the 3,200th oldest tweet and then more recent ones), which means it would skip tweets that occurred more recent than the `since_id` status but older than the 3200th status.

<sup>3</sup> To avoid returning redundant information on the status set as `since_id`, Twitter's API documentation recommends adding `1` to the status ID. In this case, we'd set `since_id = 892729976121962497`.

**Comment by mkearney** [comment] 2018-01-05 20:46
Btw, this worked for me as of rtweet v0.6.0, @Felipe1990 @JBGruber. As long as `args` in `do.call("get_timeline_", args)` contains `...`, users should be able to supply non-documented (not in rtweet, but by Twitter) parameters and those should be passed along in all requests made to Twitter's APIs. In some functions where there are no undocumented parameters, I've omitted dots from the function call. So, it's possible that added the dots only recently (it's all a blur). I'm closing this issue for now, but please let me know if you have any more issues!

**Closed by mkearney** 2018-01-05 20:46 UTC

**Comment by JBGruber** [comment] 2018-01-06 14:29
Thanks for the reply and this great package @mkearney. Unfortunately, I don't think this is solved. In your example, since_id does not do anything since you make it collect the newest 500 tweets anyway:
```
## get up to 500 tweets posted since the since_id status
rt_new <- get_timeline("kearneymw", n = 500, since_id = since_id)

## above is a special case since the 500 tweets since the the since_id status
## are simply the 500 newest tweets
rt_new2 <- get_timeline("kearneymw", n = 500)

all.equal(rt_new$status_id, rt_new2$status_id)
[1] TRUE
```

The expected behaviour of since_id is that the search would retrieve up to n tweets from the newest up to but not including the one with status_id==since_id. I came up with a different example to test if since_id is passed on correctly:
```
## install newest version
devtools::install_github("mkearney/rtweet")

## load rtweet
library(rtweet)

## get most recent 1,000 tweets from given user
rt <- get_timeline("kearneymw", n = 1000)

## subset e.g. for tweets since certain day
rt_yesterday <- rt[rt$created_at > "2018-01-05", ]

## set oldest status ID as since_id
(since_id <- as.numeric(min(rt_yesterday$status_id)))
[1] 9.493241e+17

## get up to 500 tweets posted since the since_id status
rt_yesterday2 <- get_timeline("kearneymw", n = 500, since_id = since_id)

## if since_id is passed on to API request this should be the same
all.equal(rt_yesterday$status_id[!rt_yesterday$status_id==since_id],  #remove oldest tweet since this is not caught using the since_id
          rt_yesterday2$status_id)
[1] "Lengths (36, 600) differ (string compare on first 36)"
```
As I suggested above, this is because the function `get_timeline` in "timeline.R" is not passing on the ellipsis. I just cloned your repository and made the suggested fix:
```
get_timeline <- function(user,
                         n = 100,
                         max_id = NULL,
                         home = FALSE,
                         parse = TRUE,
                         check = TRUE,
                         token = NULL,
                         ...) {
  args <- list(
    user = user,
    n = n,
    home = home,
    max_id = max_id,
    parse = parse,
    check = check,
    token = token
  )
  args <- c(args, list(...)) #This is the fix
  do.call("get_timeline_", args)
}
``` 
I'm sorry, if this is not according to the github etiquette but I'm fairly new to this. After installing the cloned repository including this fix from my hard drive, the behaviour is according to the description on the twitter API website:
```
all.equal(rt_yesterday$status_id[!rt_yesterday$status_id==since_id], #remove oldest tweet since this is not caught using the since_id
          rt_yesterday2$status_id)
[1] TRUE
```

**Comment by mkearney** [comment] 2018-01-07 17:42
@JBGruber You are totally right. I'm not sure how I overlooked that so many times lol. `get_timeline()` should now be passing the dots onto the internal functions.
