### ISSUE TITLE
Issue with Creating Token and Connecting to Dev Account

### ISSUE THREAD

**Issue by pravin-santhanam27** [mkearney/rtweet#290] opened 2018-09-07 19:15 UTC
### Problem
I am trying to connect to developer account to collect tweets. I have just been approved for the account, and I have all four of the credential codes. However, I am unable to create the token and and have the identical(token, get_token()) call to output "TRUE". I am not sure what the issue is and I have checked to make sure the keys are accurate.

### Expected behavior

identical(get_token(), token) to output TRUE

### Reproduce the problem

``` r
## insert code here

> devtools::install_github("mkearney/rtweet")
Skipping install of 'rtweet' from a github remote, the SHA1 (737e0f42) has not changed since last install.
  Use `force = TRUE` to force installation
> library(rtweet)
> 
> 
> consumer_key = "******************************************************"
> consumer_secret = "***************************************************"
> access_secret = "*******************************************************"
> access_token = "*******************************************************"
> 
> token = create_token(
+   app = "Dsch*******"
+   consumer_key = consumer_key,
+   consumer_secret = consumer_secret,
+   access_token = access_secret,
+   access_secret = access_token)
> 
> 
> identical(token, get_token())
[1] FALSE

```

### rtweet version

‘0.6.7.9000’

### Session info

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] datasets  utils     graphics  grDevices stats     methods   base     

other attached packages:
[1] rtweet_0.6.7.9000       RMySQL_0.10.15          DBI_1.0.0               dplyr_0.7.5            
[5] plyr_1.8.4              MASS_7.3-49            

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17         pillar_1.3.0         compiler_3.5.0       git2r_0.21.0         bindr_0.1.1         
 [6] iterators_1.0.9      tools_3.5.0          testthat_2.0.0       digest_0.6.15        pkgbuild_1.0.0      
[11] pkgload_1.0.0        jsonlite_1.5         memoise_1.1.0        tibble_1.4.2         debugme_1.1.0       
[16] pkgconfig_2.0.1      rlang_0.2.2          foreach_1.4.4        cli_1.0.0            rstudioapi_0.7      
[21] curl_3.2             yaml_2.1.19          bindrcpp_0.2.2       knitr_1.20           withr_2.1.2         
[26] httr_1.3.1           desc_1.2.0           devtools_1.13.5.9000 rprojroot_1.3-2      tidyselect_0.2.4    
[31] glue_1.3.0           R6_2.2.2             processx_3.1.0       purrr_0.2.5          callr_2.0.4         
[36] magrittr_1.5         backports_1.1.2      codetools_0.2-15     usethis_1.3.0        assertthat_0.2.0    
[41] openssl_1.0.2        crayon_1.3.4        

### Token

<!-- run the code below and copy/paste the output. if you don't feel comfortable 
sharing that information, then share the first 3-4 characters for the 
oauth_app ($APP_NAME$) and key ($KEY$) as they appear in the printed output 
#> <Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> Dsch****
  key:    7jn6****************
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret

``` r
## copy/paste output
rtweet::get_token()
```
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> Dsch******
  key:    7jn6****************
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret

**Comment by jdblischak** [comment] 2018-11-08 18:21
@pravin-santhanam27 I had the same confusion when I created a token for the first time. I investigated, and I think the issue is the enclosing environment attribute:

```
identical(token$.__enclos_env__, get_token()$.__enclos_env__)
```

Because the two objects were created in different enclosing environments, this will always evaluate to `FALSE`.

However, all the important information is identical, which you can test with the following:

```
identical(token$app, get_token()$app)
identical(token$credentials, get_token()$credentials)
identical(token$endpoint, get_token()$endpoint)
identical(token$params, get_token()$params)
identical(token$cache_path, get_token()$cache_path)
identical(token$private_key, get_token()$private_key)
```

In summary, I think the only way that two tokens can be completely identical is if they are created by the same function (and thus have the same closing environment):

```
identical(get_token(), get_token())
#> [1] TRUE
identical(get_token(), get_token()$clone())
#> [1] FALSE
```

**Comment by McCartneyAC** [comment] 2019-01-09 20:33
I am having similar problems. I found that @jdblischak is correct that checking the elements of the token are identical when examining them individually. 

```
> token <- create_token(
+   app = "l...",
+   consumer_key = "jhP... ",
+   consumer_secret = "...",
+   access_token = "13...-1...",
+   access_secret = "..."
+   )
> 
> identical(token$app, get_token()$app)
[1] TRUE
> identical(token$credentials, get_token()$credentials)
[1] TRUE
> identical(token$endpoint, get_token()$endpoint)
[1] TRUE
> identical(token$params, get_token()$params)
[1] TRUE
> identical(token$cache_path, get_token()$cache_path)
[1] TRUE
> identical(token$private_key, get_token()$private_key)
[1] TRUE
```




However, I still receive this error when attempting to access any twitter data, e.g. on the word "shutdown":
```
tweets <- search_tweets(q = "shutdown", n = 2000, include_rts = FALSE)
Searching for tweets...
Warning: 32 - Could not authenticate you.
Finished collecting tweets!
Warning message:
Could not authenticate you.
```

I can't tell if the problem is on the side of `rtweet` or on the side of twitter but I think I'm doing everything else correctly.

**Comment by NizMa** [comment] 2019-02-10 11:49
Hi @McCartneyAC @jdblischak @pravin-santhanam27, many thanks for posting this and sharing your feedback, ideas and solutions.
I'm new to Github — it's my first post on this platform— and the {rtweet} package, so I apologize in advance if something is unclear.
I share some of the issues you faced as well.
To start with, I don't get the TRUE return with some of the commands below.

`
token <- create_token(
+   app = "R....",
+   consumer_key = "PcK....",
+   consumer_secret = "6W....",
+   access_token = "2...-E....",
+   access_secret = "OU...")
get_token()
<Token>
<oauth_endpoint>
 request:   https://api.twitter.com/oauth/request_token
 authorize: https://api.twitter.com/oauth/authenticate
 access:    https://api.twitter.com/oauth/access_token
<oauth_app> rstats2twitter
  key:    6j7Ig4xzHlBr8uUJ5A4Ym0NTf
  secret: <hidden>
<credentials> oauth_token, oauth_token_secret, user_id, screen_name
---
`
And then I tried @jdblischak code and got the following
`identical(token$app, get_token()$app)
[1] FALSE
identical(token$credentials, get_token()$credentials)
[1] FALSE
identical(token$endpoint, get_token()$endpoint)
[1] TRUE
identical(token$params, get_token()$params)
[1] FALSE
identical(token$cache_path, get_token()$cache_path)
[1] TRUE
identical(token$private_key, get_token()$private_key)
[1] TRUE
`
So i do not know if it's working...?

However when I ran @McCartneyAC command, it seems to work (and I don't know why...)
`tweets <- search_tweets(q = "shutdown", n = 2000, include_rts = FALSE)
Searching for tweets...
Finished collecting tweets!`

Any thoughts?
Thanks

**Closed** 2019-03-07 15:45 UTC
