### ISSUE TITLE
Get error when following example

### ISSUE THREAD

**Issue by dietrichson** [mkearney/rtweet#86] opened 2017-05-25 19:49 UTC
`rt <- parse_stream('./rtweet_data/2017-05-25-16-41.json')

opening file input connection.
 Imported 10000 records. Simplifying...

closing file input connection.

Error in attr(rt, "users") <- data.frame() : 
  attempt to set an attribute on NULL`

**Comment by dietrichson** [comment] 2017-05-25 20:36
Here's minimal code to reproduce:
stream_tweets(q = "", timeout = 1800,  file_name = "rtweet-stream2", parse = FALSE)
rt <- parse_stream("rtweet-stream2.json")

**Comment by mkearney** [comment] 2017-05-25 22:17
What version of rtweet are you using? I think this is perhaps fixed in the most recent Github version:

``` r
## install from Github (dev version)
if (!"devtools" %in% installed.packages()) {
    install.packages("devtools")
}
devtools::install_github("mkearney/rtweet", build_vignettes = TRUE)
```

**Comment by dietrichson** [comment] 2017-05-25 22:46
> packageVersion("rtweet")
[1] ‘0.4.3’
I reinstalled the package and it seems to be working now - I am wondering if it might be related to the create_token function?

**Comment by mkearney** [comment] 2017-05-26 00:03
Error suggests it's not finding data, so it could be due to an issue with the token, but I think it was probably caused by a previously addressed bug in the parsing code. If it pops up again let me know!

**Closed by mkearney** 2017-05-26 00:03 UTC
