### ISSUE TITLE
search_tweets without results not working?

### ISSUE THREAD

**Issue by hoehleatsu** [mkearney/rtweet#18] opened 2016-09-17 22:15 UTC
I think there is a problem, if a search doesn't return anything:

> tw <- search_tweets("foobarfoo", n = 1200, type="recent", token = twitter_token, geocode="52.520583,13.402765,5km")
> Searching for tweets...
> Error in x[[1]] : subscript out of bounds

(if I just use foobar it works (1 result)).

Do I need to type something extra or is it a bug?

> sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.2.6

loaded via a namespace (and not attached):
[1] compiler_3.3.0 httr_1.2.1     R6_2.1.3       tools_3.3.0    curl_2.0  
[6] jsonlite_1.1   openssl_0.9.4

**Comment by mkearney** [comment] 2016-09-17 23:04
That usually means there were no search hits. Do more general search topics/terms work?

**Comment by hoehleatsu** [comment] 2016-09-17 23:20
Yes, but I don't like the function crashing with an error if there are no hits. Shouldn't it return a data.frame with zero rows, but all columns in place?

**Comment by mkearney** [comment] 2016-09-17 23:32
Oh, yes! That's on my list. I haven't put much time into error/warning messages yet, but returning a data.frame with 0 rows but all volume is smart, so I'll make sure to do that along with a warning message.

**Comment by mkearney** [comment] 2016-09-19 22:57
search_tweets should now return a data frame with 0 rows. the users data with 0 rows doesn't inherit all columns, so that's on the agenda, but I'm closing this for now.

**Comment by hoehleatsu** [comment] 2016-09-19 23:09
Thanks!

**Comment by bdilday** [comment] 2017-05-24 12:38
I've got the same issue with timelines. If the user has never tweeted, I get an error,

example,

```
> get_timeline(user = "JorgeKurius")
Error in rsp[[1]] : subscript out of bounds
```

**Comment by jimeharrisjr** [comment] 2017-06-25 02:45
I have the same issue with get_favorites

**Comment by mkearney** [comment] 2017-06-26 18:09
I'll try to incorporate httr's `stop_for_status` as per [Hadley's recommendation](88) in the next week or so. This may also require a couple additional checks for null results. The problem is Twitter returns data structures a little differently for favorites versus users versus statuses, etc.

**Comment by mkearney** [comment] 2017-07-19 20:49
Closing this as a NULL is now being returned in such situations.

``` r
> get_timeline(user = "JorgeKurius")
NULL
> get_favorites("sciencedatasci")
NULL
```

**Closed by mkearney** 2017-07-19 20:49 UTC

**Comment by CaptainKatsuura** [comment] 2017-12-30 17:08
Hi, i seem to be getting the same issue search_tweets with the following code:

results <- search_tweets("khilafat", n = 500000, include_rts = FALSE, retryonratelimit = TRUE)

on my usual Rstudio it works (despite there only a few hundred or so tweets out there)

but since i switched to RTVS using Microsoft R server i get this as a result:

Searching for tweets...
Finished collecting tweets!  #### (A few of these)
Error in rt[[i]][["status_id"]][[NROW(rt[[i]])]] : 
  subscript out of bounds

This exact code works fine in normal R studio or Microsoft R open
